development:
  adapter: mysql
  database: rearview_web_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: rearview_web_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: rearview_web_development
  username: root
  password:
  host: localhost
