development:
  adapter: mysql
  database: rearview_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: rearview_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: rearview_production
  username: root
  password:
  host: localhost
